CREATE TABLE `bot_sessions` (
	`user_id` integer PRIMARY KEY NOT NULL,
	`workout_id` integer NOT NULL,
	`chat_id` integer NOT NULL,
	`message_id` integer,
	`current_exercise_id` integer,
	`pending_weight_kg` real,
	`pending_reps` integer,
	`next_set_is_warmup` integer DEFAULT false NOT NULL,
	`ephemeral_message_id` integer,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`workout_id`) REFERENCES `workouts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`current_exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `exercises` (`user_id`, `name`, `muscle_group`, `is_custom`, `archived`) VALUES
	(NULL, 'Press de banca con barra', 'chest', 0, 0),
	(NULL, 'Press inclinado con barra', 'chest', 0, 0),
	(NULL, 'Press de banca con mancuernas', 'chest', 0, 0),
	(NULL, 'Aperturas con mancuernas', 'chest', 0, 0),
	(NULL, 'Fondos en paralelas', 'chest', 0, 0),
	(NULL, 'Cruce de poleas', 'chest', 0, 0),
	(NULL, 'Press de pecho en máquina', 'chest', 0, 0),
	(NULL, 'Press militar con barra', 'front_delt', 0, 0),
	(NULL, 'Press de hombro con mancuernas', 'front_delt', 0, 0),
	(NULL, 'Elevaciones laterales con mancuernas', 'side_delt', 0, 0),
	(NULL, 'Elevaciones laterales en polea', 'side_delt', 0, 0),
	(NULL, 'Pájaros con mancuernas', 'rear_delt', 0, 0),
	(NULL, 'Aperturas posteriores en máquina', 'rear_delt', 0, 0),
	(NULL, 'Dominadas', 'lats', 0, 0),
	(NULL, 'Jalón al pecho en polea', 'lats', 0, 0),
	(NULL, 'Remo con barra', 'lats', 0, 0),
	(NULL, 'Remo con mancuerna a una mano', 'lats', 0, 0),
	(NULL, 'Pullover en polea', 'lats', 0, 0),
	(NULL, 'Remo en máquina', 'upper_back', 0, 0),
	(NULL, 'Remo sentado en polea', 'upper_back', 0, 0),
	(NULL, 'Face pull en polea', 'upper_back', 0, 0),
	(NULL, 'Peso muerto convencional', 'lower_back', 0, 0),
	(NULL, 'Hiperextensiones', 'lower_back', 0, 0),
	(NULL, 'Buenos días con barra', 'lower_back', 0, 0),
	(NULL, 'Encogimientos con barra', 'traps', 0, 0),
	(NULL, 'Encogimientos con mancuernas', 'traps', 0, 0),
	(NULL, 'Curl con barra', 'biceps', 0, 0),
	(NULL, 'Curl con mancuernas', 'biceps', 0, 0),
	(NULL, 'Curl martillo', 'biceps', 0, 0),
	(NULL, 'Curl en banco Scott', 'biceps', 0, 0),
	(NULL, 'Extensión de tríceps en polea', 'triceps', 0, 0),
	(NULL, 'Press francés con barra', 'triceps', 0, 0),
	(NULL, 'Fondos entre bancos', 'triceps', 0, 0),
	(NULL, 'Extensión de tríceps sobre la cabeza', 'triceps', 0, 0),
	(NULL, 'Curl de muñeca con barra', 'forearms', 0, 0),
	(NULL, 'Curl de muñeca invertido', 'forearms', 0, 0),
	(NULL, 'Encogimientos abdominales', 'abs', 0, 0),
	(NULL, 'Elevación de piernas colgado', 'abs', 0, 0),
	(NULL, 'Plancha abdominal', 'abs', 0, 0),
	(NULL, 'Rueda abdominal', 'abs', 0, 0),
	(NULL, 'Sentadilla con barra', 'quads', 0, 0),
	(NULL, 'Prensa de piernas', 'quads', 0, 0),
	(NULL, 'Extensión de cuádriceps en máquina', 'quads', 0, 0),
	(NULL, 'Zancadas con mancuernas', 'quads', 0, 0),
	(NULL, 'Curl femoral tumbado', 'hamstrings', 0, 0),
	(NULL, 'Peso muerto rumano con barra', 'hamstrings', 0, 0),
	(NULL, 'Hip thrust con barra', 'glutes', 0, 0),
	(NULL, 'Patada de glúteo en polea', 'glutes', 0, 0),
	(NULL, 'Aductores en máquina', 'adductors', 0, 0),
	(NULL, 'Elevación de gemelos de pie', 'calves', 0, 0),
	(NULL, 'Elevación de gemelos sentado', 'calves', 0, 0);
